phase: tunning

tracker:
  project_name: aprendizagem_maquina_projeto

data_loader:
  name: ionosphere_KCM_K_GH

pre_processing:
  name: none

modeling:
  structure:
    name: bayes_class_knn
    k: 5
    dist_metric: euclidean # [euclidean, city_block, chebyshev]
  
  training:
    name: stratified_k_fold_tunning_train
    tunning_config: tune-bayes_knn
    n_repeats: 30

metrics:
  name: bayes_multi_classifier_metrics
