data_loader:
  name: ionosphere

pre_processing:
  name: none

modeling:
  structure:
    name: bayes_class_parzen
    h: 1.0
  
  training:
    name: stratified_k_fold
    n_repeats: 1

metrics:
  name: bayes_classifier_metrics
