phase: tunning

tracker:
  project_name: aprendizagem_maquina_projeto

data_loader:
  name: ionosphere_KCM_K_GH

pre_processing:
  name: none

modeling:
  structure:
    name: bayes_class_parzen
    h: 1.0
  
  training:
    name: stratified_k_fold_tunning_train
    tunning_config: tune-bayes_parzen
    n_repeats: 30

metrics:
  name: bayes_multi_classifier_metrics
