data_loader:
  name: ionosphere

pre_processing:
  name: none

modeling:
  structure:
    name: bayes_class
  
  training:
    name: stratified_k_fold
    target_metric: error_rate
    n_repeats: 1

metrics:
  name: bayes_classifier_metrics
