phase: tunning

data_loader:
  name: ionosphere

pre_processing:
  name: rmv_const_pre_processing

modeling:
  structure:
    name: KCM_K_GH
    n_clusters: 2
    max_iter: 100
    gamma: 1
  
  training:
    name: KCM_K_GH_tunning
    tunning_config: tune-KCM_K_GH
    n_repeats: 100

metrics:
  name: KCM_K_GH_metrics
